In [ ]:
#goal of this project is to predict which region a specific recipe is coming from
#also to make suggestions of which ingredients to add to an existing list of ingredients
#find similar recipes based on existing sample recipe

In [107]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('srep00196-s2.csv', skiprows=4)
df.head()

black_sesame_seed      rose_wine   3
0            fennel     wild_berry   5
1      comte_cheese          grape  57
2              nira       raw_beef   1
3     corn_mint_oil  parsnip_fruit   2
4           soybean  vegetable_oil   1

In [66]:
with open('srep00196-s3.csv', 'r')  as f:
    regions=[]
    ingredients=[]
    df=[]
    for rownum, row in enumerate(f):
        if(rownum<4):
            continue
        row=row.strip().split(',')
        #df.append(row)
        regions.append(row[0])
        ingredients.append(','.join(row[1:]))
regions[0], ingredients[0]

('African', 'chicken,cinnamon,soy_sauce,onion,ginger')

In [85]:
from sklearn.feature_extraction.text import CountVectorizer

cv_ingredients=CountVectorizer()
X_ingredients=cv_ingredients.fit_transform(ingredients)
ingredients_cv=cv_ingredients.build_analyzer()

cv_regions=CountVectorizer()
y_regions=cv_regions.fit_transform(regions)
regions_cv=cv_regions.build_analyzer()

region_ids=[]
for region_num, region in enumerate(regions):
    region_ids.append((region, region_num))
    
region_ids[:5]

[('African', 0),
 ('African', 1),
 ('African', 2),
 ('African', 3),
 ('African', 4)]

In [86]:
print(cv_ingredients.get_feature_names()[:5])
print(X_ingredients.toarray()[:5])

print(cv_regions.get_feature_names()[:5])
print(y_regions.toarray()[:5])

['almond', 'angelica', 'anise', 'anise_seed', 'apple']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
['african', 'eastasian', 'easterneuropean', 'latinamerican', 'middleeastern']
[[1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]]


In [88]:
region[1], ingredients[1], X_ingredients.toarray()[1]

('e',
 'cane_molasses,ginger,cumin,garlic,tamarind,bread,coriander,vinegar,onion,beef,cayenne,parsley,wheat_bread,yogurt,vegetable_oil,egg',
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [90]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [136]:
X=X_ingredients.toarray()
y=y_regions.toarray()

region_nums=[]
for row in y:
    region_nums.append(row.tolist().index(1))

region_nums=np.array(region_nums)
print(X.shape, y.shape, region_nums.shape)
print(region_nums[:5])


(56498, 381) (56498, 11) (56498,)
[0 0 0 0 0]


In [133]:
region_nums=region_nums==1
X_train, y_train, X_test, y_test = train_test_split(X, region_nums, test_size=0.3, random_state=5)
X_train.shape, y_train.shape

((39548, 381), (16950, 381))

In [130]:
lr=LogisticRegression()
lr.fit(X_train, y_train)

ValueError: bad input shape (16950, 381)